### ISSUE TITLE
Only Inbox folder size is shown

### ISSUE THREAD

**Issue by javildn** [jfcherng/roundcube-plugin-show-folder-size#1]
Hi, I tried your plugin but it only shows the size of the Inbox folder.

**Comment by jfcherng** [comment]
What if using the default theme?

**Comment by sai-mike** [comment]
I have the same issue.  The plugin only shows the size of my Inbox and Archive folders.  My normal skin is Classic, but the same problem occurs if I use Larry.  The same problem also occurs with 'auto_show_folder_size' => false, or true.

![Selection_001](https://user-images.githubusercontent.com/35618397/59808911-250e3480-92b3-11e9-93f4-0b75bb24ac63.png)

**Comment by jfcherng** [comment]
@sai-mike I wonder this could be due to different mailing backend or I wrote the plugin in potentially wrong way.

![image](https://user-images.githubusercontent.com/6594915/59811269-b32dfd80-933b-11e9-99af-a22cb1cb3399.png)

Could you see (and click) the `Click to get folder size` for your `Sent` folder?

**Comment by sai-mike** [comment]
Here it is:

![Selection_001](https://user-images.githubusercontent.com/35618397/59811973-fc8d3700-92c0-11e9-85e7-49866a99736c.png)

**Comment by jfcherng** [comment]
@sai-mike Would you like to test 9ba8c801bf0a96b587a84cca8445ccce00cfdde3 (or just use the master branch)? It works for me on my machine to show subfolder's size.

**Comment by sai-mike** [comment]
I installed dev-master:

Package operations: 0 installs, 1 update, 0 removals
  - Removing jfcherng/show-folder-size (0.2.6)
  - Installing jfcherng/show-folder-size (dev-master 2b737f2): Cloning 2b737f2760

This fixed the problem with top level mail folders:

![Selection_002](https://user-images.githubusercontent.com/35618397/59879585-e5515680-935f-11e9-8784-b490c7a5a8b0.png)

However, second level sub-folders have duplicate sizes and number of items displayed:

![Selection_001](https://user-images.githubusercontent.com/35618397/59879637-02862500-9360-11e9-9734-3c9ef73585b2.png)

**Comment by sai-mike** [comment]
Additional info.  I have 'auto_show_folder_size' => false, and the display differes when I click the toolbar button depending on whether the subfolders are expanded and visible, or not, when I click the toolbar button.

If the subfolders are collapsed and I click the button, I get:

![Selection_002](https://user-images.githubusercontent.com/35618397/59880431-dcfa1b00-9361-11e9-92a3-10d710bc92f1.png)
 
And if the subfolders are expanded when I click the button, I get this:

![Selection_003](https://user-images.githubusercontent.com/35618397/59880463-f0a58180-9361-11e9-8075-97de60a67de9.png)

**Comment by jfcherng** [comment]
@sai-mike I have push version `0.2.8` which reduces the numbers of issued HTTP requests to only one. And during doing that, I found that RC's PHP API somehow return duplicated folders. I have dealt that and I think I may related to your "second level sub-folders" issue. Please let me know if `0.2.8` works for you.

**Comment by sai-mike** [comment]
Same problem with 0.2.8

Starting point - Suppliers folder collapsed:

![Selection_001](https://user-images.githubusercontent.com/35618397/59884717-002ac780-936e-11e9-8285-d2c275d44a3c.png)

Click toolbar button, expand Suppliers folder, expand Business folder. If top level folder is collasped when button is clicked, both second & third level have duplicates:

![Selection_002](https://user-images.githubusercontent.com/35618397/59884808-3bc59180-936e-11e9-839d-2544d6712afd.png)

Starting point - Suppliers folder expanded, Business folder collapsed:

![Selection_003](https://user-images.githubusercontent.com/35618397/59884889-6879a900-936e-11e9-8092-bf59cf4bfc20.png)

Click toolbar button and now it looks like this:

![Selection_004](https://user-images.githubusercontent.com/35618397/59884940-8c3cef00-936e-11e9-9f5d-57797188760b.png)

Expand Business and now we have duplicates again at third level only because second level was expanded when toolbar button was clicked:

![Selection_005](https://user-images.githubusercontent.com/35618397/59884974-a37bdc80-936e-11e9-9a49-8fab05ae70e0.png)

**Comment by jfcherng** [comment]
Hmm... after some test, this seems to happen only when using `classic` skin.

**Comment by sai-mike** [comment]
I just switched over to the Larry skin and I can verify it also works correctly for me with Larry.

**Comment by jfcherng** [comment]
I believe this has been fixed in `0.3.0`. Due to Composer's semver strategy, you may have to manually modify `composer.json` to use the following if you cannot upgrade this plugin.

```
"composer require jfcherng/show-folder-size": "~0.3"
```

Let me know if `0.3.0` works. I am going to close this issue. If there is another issue, open another one for it.

**Comment by sai-mike** [comment]
There is no 0.3.0 release.  Should I install dev-master?

**Comment by sai-mike** [comment]
Problem looks like it is fixed with the Classic skin in current dev-master.

**Comment by jfcherng** [comment]
> There is no 0.3.0 release. Should I install dev-master?

Ah. I forgot to push the git tag. Glad it works.
